*** empty log message ***
git-svn-id: https://emacspeak.googlecode.com/svn/trunk@856 bb5eec90-091a-0410-bc89-db79c2cf2c7b

diff --git a/emacspeak/etc/ppt2html b/emacspeak/etc/ppt2html
--- a/emacspeak/etc/ppt2html
+++ b/emacspeak/etc/ppt2html
@@ -8,6 +8,9 @@ then
     cat > $tempfile
     ppthtml   $tempfile
     rm -f $tempfile
+    exit 0
 else
-    echo "ppthtml not found --install package xlhtml from http://www.xlhtml.org."
+    echo "ppthtml not found --install package xlhtml from
+#http://www.xlhtml.org."
+    exit 1
 fi
diff --git a/emacspeak/etc/xls2html b/emacspeak/etc/xls2html
--- a/emacspeak/etc/xls2html
+++ b/emacspeak/etc/xls2html
@@ -8,6 +8,9 @@ then
     cat > $tempfile
     xlhtml -a -te  $tempfile
     rm -f $tempfile
+    exit 0
 else
-    echo "xlhtml not found --install package xlhtml from http://www.xlhtml.org."
+    echo "xlhtml not found --install package xlhtml from
+#http://www.xlhtml.org."
+    exit 1
 fi
